### ISSUE TITLE
Can I save the plots as pdf or png file with some customization?

### ISSUE THREAD

**Issue by therimalaya** [olivertomic/hoggormPlot#11]
Thanks for the libraries.

All the examples you have setup in the documentation directly output the plot. Is there any way I can save the plots directly as pdf or png file as in `savefig` of matplotlib. That would be really helpful. In addition, some option to customize the plot such as figure size or font size would be nice.

**Comment by olivertomic** [comment]
Thank you for your suggestions **therimalaya**. In the next release there should definitively be an input parameter in the main plot function such as `saveFigure` with options `True` or `False` and and additional parameters for plot format and plot size.

**Comment by olivertomic** [comment]
What I forgot to mention, there is a primitive workaround to saving the plots with a desired size and format. If you are using the Spyder editor you can run your script in an external console (Spyder main menu: "Run" -> "Configuration per file" -> In the window popping up in the section "Console"select "Execute in an external system terminal"). 
Running your script this way will produce plots one-by-one in own windows that can be resized and saved in the desired plot format.

**Comment by therimalaya** [comment]
Thank you Oliver for the suggestion and quick reply. I will go for this option if need to save the plots for now.

**Comment by olivertomic** [comment]
Your pull request has been merged into the master. Thank you for your contribution, Raju.
