### ISSUE TITLE
Error in plot of Explained Variance

### ISSUE THREAD

**Issue by runhel** [olivertomic/hoggormPlot#16]
The blue line in the explained variance plot is defined in the legend as 'Calidated explained variance' and not 'Calibrated explained variance'.

**Comment by olivertomic** [comment]
Thank you for reporting this typo. :-)

**Comment by runhel** [comment]
No problem. It was actually Linda who discovered it while using the Hoggorm in her thesis. We thought it would be nice to report it to you :)

**Comment by olivertomic** [comment]
Fixed now! :-)
